import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#004976",
        "primary-container": "#00629b",
        "primary-fixed": "#cee5ff",
        "primary-fixed-dim": "#98cbff",
        "on-primary": "#ffffff",
        "on-primary-container": "#badbff",
        "on-primary-fixed": "#001d33",
        "on-primary-fixed-variant": "#004a77",
        secondary: "#1b6d24",
        "secondary-container": "#a0f399",
        "secondary-fixed": "#a3f69c",
        "secondary-fixed-dim": "#88d982",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#217128",
        "on-secondary-fixed": "#002204",
        "on-secondary-fixed-variant": "#005312",
        tertiary: "#004e59",
        "tertiary-container": "#006875",
        "tertiary-fixed": "#9eefff",
        "tertiary-fixed-dim": "#55d7ed",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#6be9ff",
        "on-tertiary-fixed": "#001f24",
        "on-tertiary-fixed-variant": "#004e59",
        background: "#f7fafc",
        surface: "#f7fafc",
        "surface-bright": "#f7fafc",
        "surface-dim": "#d7dadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "surface-container": "#ebeef0",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#02639c",
        "on-surface": "#181c1e",
        "on-surface-variant": "#414750",
        "on-background": "#181c1e",
        outline: "#717881",
        "outline-variant": "#c0c7d1",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#98cbff",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eef1f3",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      fontFamily: {
        sans: ["Public Sans", "sans-serif"],
        headline: ["Public Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
      boxShadow: {
        soft: "0 12px 40px rgba(0, 73, 118, 0.08)",
      },
    },
  },
  plugins: [forms, containerQueries],
};
